import React from 'react'
import {Container,Content,Header,Card,CardItem,Text, Left, Button, Icon, Body} from 'native-base';
import { TouchableOpacity } from 'react-native-gesture-handler';

export default function privacyPolicy ({navigation}){
    return(
      <Container>
          <Header transparent >
              <Left>
                  <TouchableOpacity onPress={()=>navigation.navigate('profileMain')}>
                  <Button bordered info>
                      <Icon name='arrow-back'/>
                  </Button>
                  </TouchableOpacity>
              </Left>
              <Body>
            <Text style={{fontSize:24}}>Privacy Policy</Text> 
            </Body>
          </Header>
          <Content>
              <Card>
              <CardItem header>
              <Text style={{fontWeight:'bold'}}>Privacy Policy</Text>
            </CardItem>
            <CardItem>
              <Body>
                <Text>
                01.
Effective date: July 13, 2019
                </Text>
                <Text>
                Snapinsight ("us", "we", or "our") operates the https://snapinsight.net website (hereinafter referred to as the "Service").
                </Text>
                <Text>
                This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</Text>
<Text>
We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://snapinsight.net
                </Text>
              </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Definitions</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>
                    Service is the https://snapinsight.net website operated by Snapinsight
                    </Text>
                    <Text>
                    Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                    </Text>
                    <Text>
                    Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).


                    </Text>
                    <Text>
                        
                        Cookies are small files stored on your device (computer or mobile device).
                    </Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Information Collection and Use</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                    </Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Security of Data</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>
                    The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                    </Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Service Providers</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.

These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</Text>
                    <Text>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.

You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js and dc.js) from sharing information with Google Analytics about visits activity.

For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page: https://policies.google.com/privacy?hl=en

This website abides and follows the GDPR regulations provided in the following link. Visit the site for detailed information.
GDPR Regulations</Text>
                    <Text>This website abides and follows the Assembly Bill No. 370 , CHAPTER 390 (Consumers:Internet Privacy ) Regulations as mentioned below
An act to amend Section 22575 of the Business and Professions Code, relating to consumers.
[ Approved by Governor September 27, 2013. Filed with Secretary of State September 27, 2013. ]</Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>AB 370, Muratsuchi. Consumers: internet privacy.</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>Existing law requires an operator of a commercial Internet Web site or online service that collects personally identifiable information through the Internet about consumers residing in California who use or visit its commercial Web site or online service to conspicuously post its privacy policy on its Web site or online service and to comply with that policy. Existing law, among other things, requires that the privacy policy identify the categories of personally identifiable information that the operator collects about individual consumers who use or visit its Web site or online service and 3rd parties with whom the operator shares the information.

This bill would require an operator to disclose how it responds to “do not track” signals or other mechanisms that provide consumers a choice regarding the collection of personally identifiable information about an individual consumer’s online activities over time and across different Web sites or online services. The bill would require the operator to disclose whether other parties may collect personally identifiable information when a consumer uses the operator’s Web site or service.</Text>
                    <Text>DIGEST KEY</Text>
                    <Text>Vote: majority Appropriation: no Fiscal Committee: no Local Program: no
BILL TEXT
THE PEOPLE OF THE STATE OF CALIFORNIA DO ENACT AS FOLLOWS:</Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>SECTION 1. Section 22575 of the Business and Professions Code is amended to read:</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>22575. (a) An operator of a commercial Web site or online service that collects personally identifiable information through the Internet about individual consumers residing in California who use or visit its commercial Web site or online service shall conspicuously post its privacy policy on its Web site, or in the case of an operator of an online service, make that policy available in accordance with paragraph (5) of subdivision (b) of Section 22577. An operator shall be in violation of this subdivision only if the operator fails to post its policy within 30 days after being notified of noncompliance.
(b) The privacy policy required by subdivision (a) shall do all of the following:
(1) Identify the categories of personally identifiable information that the operator collects through the Web site or online service about individual consumers who use or visit its commercial Web site or online service and the categories of third-party persons or entities with whom the operator may share that personally identifiable information.
(2) If the operator maintains a process for an individual consumer who uses or visits its commercial Web site or online service to review and request changes to any of his or her personally identifiable information that is collected through the Web site or online service, provide a description of that process.
(3) Describe the process by which the operator notifies consumers who use or visit its commercial Web site or online service of material changes to the operator’s privacy policy for that Web site or online service.
(4) Identify its effective date.
(5) Disclose how the operator responds to Web browser “do not track” signals or other mechanisms that provide consumers the ability to exercise choice regarding the collection of personally identifiable information about an individual consumer’s online activities over time and across third-party Web sites or online services, if the operator engages in that collection.
(6) Disclose whether other parties may collect personally identifiable information about an individual consumer’s online activities over time and across different Web sites when a consumer uses the operator’s Web site or service.
(7) An operator may satisfy the requirement of paragraph (5) by providing a clear and conspicuous hyperlink in the operator’s privacy policy to an online location containing a description, including the effects, of any program or protocol the operator follows that offers the consumer that choice.</Text>
                    <Text style={{fontWeight:'bold'}}>Links to Other Sites</Text>
                    <Text>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.

We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</Text>

                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Children's Privacy</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>Our Service does not address anyone under the age of 18 ("Children").

We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</Text>
                </Body>
            </CardItem>
            <CardItem header>
                <Text style={{fontWeight:'bold'}}>Changes to This Privacy Policy</Text>
            </CardItem>
            <CardItem>
                <Body>
                    <Text>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy.

You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page</Text>
                </Body>
            </CardItem>
            <CardItem footer>
              <Text style={{fontWeight:'bold'}}>Contact Us</Text>
              </CardItem>
              <CardItem footer>
              <Text>If you have any questions about this Privacy Policy, please contact us:

By email: snapinsight0@gmail.com</Text>
            </CardItem>
              </Card>
          </Content>
      </Container>
    )
}